apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: incident-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: incidents
            - name: POSTGRES_USER
              value: incidents_user
            - name: POSTGRES_PASSWORD
              value: incidents_pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "incidents_user", "-d", "incidents"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: incident-tracker
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
